{{- $root := . -}}
{{- range .Values.cronjobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "banzai-floyds.fullname" $root -}}-{{ .site -}}-cronjob"
  labels:
{{ include "banzai-floyds.labels" $root | indent 4 }}
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "banzai-floyds.name" $root }}
        app.kubernetes.io/instance: "{{ $root.Release.Name }}"
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "banzai-floyds.name" $root }}
            app.kubernetes.io/instance: "{{ $root.Release.Name }}"
        spec:
          containers:
          - name: "banzai-floyds-stack-flats-{{ .site }}"
            image: "{{ $root.Values.image.repository }}:{{ $root.Values.image.tag }}"
            imagePullPolicy: {{ $root.Values.image.pullPolicy }}
            securityContext:
              runAsUser: 10087
              runAsGroup: 10000
            env:
              {{- include "banzaiFloyds.Env" $root | nindent 12 }}
            args:
            - banzai_floyds_stack_flats
            - --site {{ .site }}
            - "--post-to-archive"
            - "--post-to-opensearch"
            - "--fpack"
            - "--rlevel=91"
            - "--db-address=$(DB_ADDRESS)"
            - "--no-file-cache"
          restartPolicy: Never
{{- end }}
