"""Adding the profile shape table

Revision ID: 6ca788a6690c
Revises: c9519d6ec8f5
Create Date: 2026-09-16 13:44:58.662341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca788a6690c'
down_revision: Union[str, Sequence[str], None] = 'c9519d6ec8f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profileshape',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('instrument_id', sa.Integer(), nullable=True),
        sa.Column('filename', sa.String(length=100), nullable=True),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('slit_width', sa.Float(), nullable=True),
        sa.Column('dateobs', sa.DateTime(), nullable=True),
        sa.Column('wavelength_min', sa.Float(), nullable=True),
        sa.Column('wavelength_max', sa.Float(), nullable=True),
        sa.Column('fwhm_c0', sa.Float(), nullable=True),
        sa.Column('fwhm_c1', sa.Float(), nullable=True),
        sa.Column('fwhm_c2', sa.Float(), nullable=True),
        sa.Column('gamma_c0', sa.Float(), nullable=True),
        sa.Column('gamma_c1', sa.Float(), nullable=True),
        sa.Column('good_until', sa.DateTime(), nullable=True),
        sa.Column('good_after', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profileshape_instrument_id'), 'profileshape', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profileshape_instrument_id'), table_name='profileshape')
    op.drop_table('profileshape')
    # ### end Alembic commands ###
